import React from 'react'
import { AnimationStep } from '../types'

type Props = {
  steps: AnimationStep[]
  onAccept: () => void
  onReject: () => void
}

export default function AutoSuggestModal({ steps, onAccept, onReject }: Props) {
  return (
    <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="suggest-title">
      <div className="modal-card">
        <header className="modal-header">
          <h3 id="suggest-title">Suggested animation sequence</h3>
          <p>
            Generated by walking connected nodes in your diagram (BFS). Review before applying.
          </p>
        </header>

        <ol className="suggest-preview-list">
          {steps.map((step, index) => (
            <li key={step.id}>
              <span className="suggest-preview-num">{index + 1}</span>
              <div>
                <strong>{step.label}</strong>
                <span className="suggest-preview-meta">
                  {step.highlight.length} node{step.highlight.length !== 1 ? 's' : ''},{' '}
                  {step.flow.length} line{step.flow.length !== 1 ? 's' : ''}
                </span>
              </div>
            </li>
          ))}
        </ol>

        <footer className="modal-footer">
          <button type="button" className="ghost" onClick={onReject}>
            Cancel
          </button>
          <button type="button" onClick={onAccept}>
            Apply {steps.length} steps
          </button>
        </footer>
      </div>
    </div>
  )
}
