import React, { useEffect, useMemo, useState } from 'react'
import { AnimationStep } from '../types'

type Props = {
  steps: AnimationStep[]
  onAccept: (steps: AnimationStep[]) => void
  onReject: () => void
}

export default function AutoSuggestModal({ steps, onAccept, onReject }: Props) {
  const [selectedIds, setSelectedIds] = useState(() => new Set(steps.map((step) => step.id)))

  useEffect(() => {
    setSelectedIds(new Set(steps.map((step) => step.id)))
  }, [steps])

  const selectedSteps = useMemo(
    () => steps.filter((step) => selectedIds.has(step.id)),
    [selectedIds, steps]
  )

  return (
    <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="suggest-title">
      <div className="modal-card">
        <header className="modal-header">
          <h3 id="suggest-title">Suggested animation sequence</h3>
          <p>
            Generated by walking connected nodes in your diagram (BFS). Review before applying.
          </p>
        </header>

        <ol className="suggest-preview-list">
          {steps.map((step, index) => (
            <li key={step.id} className={!selectedIds.has(step.id) ? 'is-deselected' : ''}>
              <label className="suggest-preview-toggle">
                <input
                  type="checkbox"
                  checked={selectedIds.has(step.id)}
                  onChange={() => {
                    setSelectedIds((current) => {
                      const next = new Set(current)
                      if (next.has(step.id)) next.delete(step.id)
                      else next.add(step.id)
                      return next
                    })
                  }}
                  aria-label={`Include ${step.label}`}
                />
                <span className="suggest-preview-num">{index + 1}</span>
              </label>
              <div>
                <strong>{step.label}</strong>
                <span className="suggest-preview-meta">
                  {step.highlight.length} node{step.highlight.length !== 1 ? 's' : ''},{' '}
                  {step.flow.length} line{step.flow.length !== 1 ? 's' : ''}
                </span>
                <span className="suggest-preview-meta">
                  {step.highlight.length > 0 ? `Node animation: ${step.nodeAnimation}` : ''}
                  {step.highlight.length > 0 && step.flow.length > 0 ? ' · ' : ''}
                  {step.flow.length > 0 ? `Line animation: ${step.edgeAnimation}` : ''}
                </span>
              </div>
            </li>
          ))}
        </ol>

        <footer className="modal-footer">
          <button type="button" className="ghost" onClick={onReject}>
            Cancel
          </button>
          <button type="button" onClick={() => onAccept(selectedSteps)} disabled={selectedSteps.length === 0}>
            Apply {selectedSteps.length} steps
          </button>
        </footer>
      </div>
    </div>
  )
}
